import type {
  TeachingKnowledgeEdge,
  TeachingKnowledgeNode,
  TeachingLearningEvent,
  TeachingStudentProfile,
} from './types';

export const DEFAULT_TEACHING_COURSE_ID = 'embodied-intelligence';

export const defaultTeachingCourse = {
  id: DEFAULT_TEACHING_COURSE_ID,
  title: '具身智能课程',
  description:
    '面向具身智能导论课程，覆盖环境感知、世界模型、任务规划、运动规划、操作控制和多智能体协同。',
};

export const defaultKnowledgeNodes: TeachingKnowledgeNode[] = [
  {
    id: 'kp-camera-model',
    title: '相机模型与标定',
    chapterId: 'ch1',
    chapterTitle: '第一章 环境感知',
    sectionId: 'ch1-s1',
    sectionTitle: '1.1 传感器基础',
    level: 'knowledge',
    dependencies: [],
    masteryBaseline: 82,
    orderIndex: 1,
  },
  {
    id: 'kp-lidar',
    title: '激光雷达原理',
    chapterId: 'ch1',
    chapterTitle: '第一章 环境感知',
    sectionId: 'ch1-s1',
    sectionTitle: '1.1 传感器基础',
    level: 'knowledge',
    dependencies: [],
    masteryBaseline: 72,
    orderIndex: 2,
  },
  {
    id: 'kp-kalman',
    title: '卡尔曼滤波',
    chapterId: 'ch1',
    chapterTitle: '第一章 环境感知',
    sectionId: 'ch1-s2',
    sectionTitle: '1.2 多传感器融合',
    level: 'knowledge',
    dependencies: ['kp-camera-model', 'kp-lidar'],
    masteryBaseline: 62,
    orderIndex: 3,
  },
  {
    id: 'kp-icp',
    title: '点云配准 ICP',
    chapterId: 'ch1',
    chapterTitle: '第一章 环境感知',
    sectionId: 'ch1-s2',
    sectionTitle: '1.2 多传感器融合',
    level: 'knowledge',
    dependencies: ['kp-lidar'],
    masteryBaseline: 48,
    orderIndex: 4,
  },
  {
    id: 'kp-yolo',
    title: '目标检测 YOLO',
    chapterId: 'ch1',
    chapterTitle: '第一章 环境感知',
    sectionId: 'ch1-s3',
    sectionTitle: '1.3 语义感知',
    level: 'knowledge',
    dependencies: ['kp-camera-model'],
    masteryBaseline: 76,
    orderIndex: 5,
  },
  {
    id: 'kp-world-model',
    title: '世界模型定义与发展',
    chapterId: 'ch2',
    chapterTitle: '第二章 世界模型',
    sectionId: 'ch2-s1',
    sectionTitle: '2.1 世界模型概述',
    level: 'knowledge',
    dependencies: ['kp-kalman', 'kp-yolo'],
    masteryBaseline: 58,
    orderIndex: 6,
  },
  {
    id: 'kp-dreamer',
    title: 'Dreamer 系列模型',
    chapterId: 'ch2',
    chapterTitle: '第二章 世界模型',
    sectionId: 'ch2-s1',
    sectionTitle: '2.1 世界模型概述',
    level: 'knowledge',
    dependencies: ['kp-world-model'],
    masteryBaseline: 38,
    orderIndex: 7,
  },
  {
    id: 'kp-llm-world',
    title: 'LLM 作为世界模型',
    chapterId: 'ch2',
    chapterTitle: '第二章 世界模型',
    sectionId: 'ch2-s2',
    sectionTitle: '2.2 基于大语言模型的世界模型',
    level: 'knowledge',
    dependencies: ['kp-world-model'],
    masteryBaseline: 34,
    orderIndex: 8,
  },
  {
    id: 'kp-htn',
    title: 'HTN 层级任务网络',
    chapterId: 'ch3',
    chapterTitle: '第三章 任务规划',
    sectionId: 'ch3-s1',
    sectionTitle: '3.1 任务分解与层级规划',
    level: 'knowledge',
    dependencies: ['kp-llm-world'],
    masteryBaseline: 52,
    orderIndex: 9,
  },
  {
    id: 'kp-llm-planning',
    title: 'LLM 任务规划',
    chapterId: 'ch3',
    chapterTitle: '第三章 任务规划',
    sectionId: 'ch3-s1',
    sectionTitle: '3.1 任务分解与层级规划',
    level: 'knowledge',
    dependencies: ['kp-htn'],
    masteryBaseline: 45,
    orderIndex: 10,
  },
  {
    id: 'kp-rrt-prm',
    title: 'RRT 与 PRM',
    chapterId: 'ch3',
    chapterTitle: '第三章 任务规划',
    sectionId: 'ch3-s2',
    sectionTitle: '3.2 Motion Planning',
    level: 'knowledge',
    dependencies: ['kp-htn'],
    masteryBaseline: 35,
    orderIndex: 11,
  },
  {
    id: 'kp-trajectory',
    title: '轨迹优化',
    chapterId: 'ch3',
    chapterTitle: '第三章 任务规划',
    sectionId: 'ch3-s2',
    sectionTitle: '3.2 Motion Planning',
    level: 'knowledge',
    dependencies: ['kp-rrt-prm'],
    masteryBaseline: 28,
    orderIndex: 12,
  },
  {
    id: 'kp-grasp',
    title: '抓取规划',
    chapterId: 'ch3',
    chapterTitle: '第三章 任务规划',
    sectionId: 'ch3-s3',
    sectionTitle: '3.3 Manipulation',
    level: 'knowledge',
    dependencies: ['kp-trajectory'],
    masteryBaseline: 22,
    orderIndex: 13,
  },
  {
    id: 'kp-force-control',
    title: '力控与柔顺控制',
    chapterId: 'ch3',
    chapterTitle: '第三章 任务规划',
    sectionId: 'ch3-s3',
    sectionTitle: '3.3 Manipulation',
    level: 'knowledge',
    dependencies: ['kp-grasp'],
    masteryBaseline: 18,
    orderIndex: 14,
  },
  {
    id: 'kp-mdp',
    title: 'MDP 与价值函数',
    chapterId: 'ch4',
    chapterTitle: '第四章 多智能体协同',
    sectionId: 'ch4-s1',
    sectionTitle: '4.1 强化学习基础',
    level: 'knowledge',
    dependencies: ['kp-world-model'],
    masteryBaseline: 50,
    orderIndex: 15,
  },
  {
    id: 'kp-ppo',
    title: 'PPO 算法',
    chapterId: 'ch4',
    chapterTitle: '第四章 多智能体协同',
    sectionId: 'ch4-s1',
    sectionTitle: '4.1 强化学习基础',
    level: 'knowledge',
    dependencies: ['kp-mdp'],
    masteryBaseline: 42,
    orderIndex: 16,
  },
  {
    id: 'kp-marl',
    title: 'MARL 框架',
    chapterId: 'ch4',
    chapterTitle: '第四章 多智能体协同',
    sectionId: 'ch4-s2',
    sectionTitle: '4.2 多智能体强化学习',
    level: 'knowledge',
    dependencies: ['kp-ppo'],
    masteryBaseline: 24,
    orderIndex: 17,
  },
  {
    id: 'kp-coordination',
    title: '协作与竞争策略',
    chapterId: 'ch4',
    chapterTitle: '第四章 多智能体协同',
    sectionId: 'ch4-s2',
    sectionTitle: '4.2 多智能体强化学习',
    level: 'knowledge',
    dependencies: ['kp-marl'],
    masteryBaseline: 18,
    orderIndex: 18,
  },
];

export const defaultKnowledgeEdges: TeachingKnowledgeEdge[] = defaultKnowledgeNodes.flatMap((node) =>
  node.dependencies.map((source) => ({
    source,
    target: node.id,
    relation: 'prerequisite' as const,
  })),
);

export const defaultStudents: TeachingStudentProfile[] = [
  {
    id: '2024001',
    name: '张明',
    goal: '补齐运动规划和操作控制基础，能够独立完成 MoveIt 实验。',
    level: '基础偏弱但学习意愿强',
    preferences: { pace: '循序渐进', style: '案例类比', resourcePriority: 'practice' },
  },
  {
    id: '2024005',
    name: '刘洋',
    goal: '深化世界模型与多智能体强化学习，准备课程项目展示。',
    level: '基础扎实',
    preferences: { pace: '快速', style: '理论推导', resourcePriority: 'paper' },
  },
  {
    id: '2024006',
    name: '陈静',
    goal: '把算法原理和机器人应用案例连接起来。',
    level: '中等偏上',
    preferences: { pace: '标准', style: '实验优先', resourcePriority: 'visual' },
  },
  {
    id: '2024007',
    name: '王浩',
    goal: '掌握任务规划链路，提升练习正确率。',
    level: '中等',
    preferences: { pace: '标准', style: '启发式提问', resourcePriority: 'balanced' },
  },
  {
    id: '2024008',
    name: '李雪',
    goal: '跟上课程进度，减少概念混淆。',
    level: '中等偏弱',
    preferences: { pace: '循序渐进', style: '图示说明', resourcePriority: 'visual' },
  },
];

function daysAgo(dayOffset: number, hour = 10): string {
  const date = new Date();
  date.setDate(date.getDate() - dayOffset);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

const event = (
  id: string,
  studentId: string,
  eventType: TeachingLearningEvent['eventType'],
  knowledgeNodeId: string,
  score: number | null,
  durationMinutes: number,
  dayOffset: number,
  payload: Record<string, unknown> = {},
): TeachingLearningEvent => ({
  id,
  studentId,
  eventType,
  knowledgeNodeId,
  score,
  durationMinutes,
  occurredAt: daysAgo(dayOffset, 9 + (Number(id.replace(/\D/g, '').slice(-1)) % 9)),
  payload,
});

export const defaultLearningEvents: TeachingLearningEvent[] = [
  event('ev-001', '2024001', 'study', 'kp-camera-model', 84, 35, 14),
  event('ev-002', '2024001', 'practice', 'kp-kalman', 78, 28, 10),
  event('ev-003', '2024001', 'qa', 'kp-rrt-prm', 42, 12, 5, {
    question: 'RRT 和 PRM 的区别是什么？',
  }),
  event('ev-004', '2024001', 'practice', 'kp-rrt-prm', 35, 25, 4),
  event('ev-005', '2024001', 'quiz', 'kp-trajectory', 32, 20, 3),
  event('ev-006', '2024001', 'qa', 'kp-grasp', 25, 10, 2, {
    question: '抓取规划为什么要考虑接触力？',
  }),
  event('ev-007', '2024001', 'review', 'kp-kalman', 82, 20, 1),
  event('ev-008', '2024001', 'practice', 'kp-ppo', 46, 18, 1),

  event('ev-101', '2024005', 'study', 'kp-world-model', 86, 45, 6),
  event('ev-102', '2024005', 'practice', 'kp-dreamer', 78, 35, 4),
  event('ev-103', '2024005', 'quiz', 'kp-ppo', 92, 30, 2),
  event('ev-104', '2024005', 'qa', 'kp-marl', 84, 12, 1, {
    question: '集中式训练分布式执行如何实现？',
  }),

  event('ev-201', '2024006', 'study', 'kp-kalman', 88, 35, 7),
  event('ev-202', '2024006', 'practice', 'kp-icp', 72, 25, 5),
  event('ev-203', '2024006', 'practice', 'kp-rrt-prm', 76, 30, 3),
  event('ev-204', '2024006', 'quiz', 'kp-grasp', 70, 24, 1),

  event('ev-301', '2024007', 'study', 'kp-htn', 70, 32, 8),
  event('ev-302', '2024007', 'qa', 'kp-llm-planning', 62, 10, 4, {
    question: 'LLM 任务规划如何避免幻觉？',
  }),
  event('ev-303', '2024007', 'practice', 'kp-rrt-prm', 64, 28, 2),
  event('ev-304', '2024007', 'quiz', 'kp-trajectory', 58, 20, 1),

  event('ev-401', '2024008', 'study', 'kp-world-model', 60, 30, 9),
  event('ev-402', '2024008', 'qa', 'kp-dreamer', 48, 12, 6, {
    question: 'Dreamer 的 latent dynamics 是什么？',
  }),
  event('ev-403', '2024008', 'practice', 'kp-rrt-prm', 52, 24, 3),
  event('ev-404', '2024008', 'quiz', 'kp-grasp', 46, 18, 1),
];
